name = input("Ingresa el precio del Dolar: ")
total = input("Ingresa el total de pesos MXN: ")
print(f"Dolar {name} y tengo {total} pesos MXN")
future = int(total) * int(name)
print(f"En total de pesos MXN tendré {future} dolares")